apps/tm/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import AddReviewProposal
from .views import AnonymizeDataProgressView
from .views import AnonymizeDataView
from .views import AssignmentAcceptance
from .views import AssignmentsListView
from .views import AssignmentsToValidateListView
from .views import AttemptAutocomplete
from .views import AttemptDetailView
from .views import CalendarDetailView
from .views import DashboardView
from .views import DefenseBookRoomUpdateView
from .views import DefenseCreateView
from .views import DefenseRemediationObjectives
from .views import DefensesListView
from .views import DefenseSubmitAssessment
from .views import DefenseSubmitStatementOfFees
from .views import DeleteStepFromProposal
from .views import DispositionCreateView
from .views import DispositionDetailView
from .views import DispositionEvaluateMethodologyView
from .views import DispositionEvaluateView
from .views import DispositionListView
from .views import DispositionSubmitView
from .views import DispositionUpdateView
from .views import ExpertListView
from .views import GroupsListView
from .views import ImportExportDocumentsView
from .views import ImportStudentsProgressView
from .views import ImportStudentsView
from .views import LibraryDetailView
from .views import LibraryListView
from .views import OverviewView
from .views import PersonalLeaveCreateView
from .views import PersonalLeaveDeleteView
from .views import PersonalLeaveListView
from .views import PersonalLeaveUpdateView
from .views import ProgressReportCreateView
from .views import ProgressReportDetailView
from .views import ProgressReportListView
from .views import ProgressReportSubmitView
from .views import ProgressReportUpdateView
from .views import ProgressReportView
from .views import ProposalCreateView
from .views import ProposalDetailView
from .views import ProposalExportView
from .views import ProposalListView
from .views import ProposalUpdateView
from .views import StudentExceptionCreateView
from .views import StudentExceptionDetailView
from .views import StudentExceptionListView
from .views import StudentExceptionUpdateView
from .views import SubmitProposal
from .views import SupervisorAutocomplete
from .views import SupervisorSuggestion
from .views import ThesesListView
from .views import ThesesMailingView
from .views import ThesisDetailView
from .views import ThesisExpertAcceptView
from .views import ThesisExpertDeclineView
from .views import ThesisExpertDetailView
from .views import ThesisRecordAuthorizationPublish
from .views import ThesisSubmitAuthorizationPublish
from .views import ThesisSubmitView
from .views import ThesisUpdateView
from .views import WithdrawProposal
from .views import add_supervisor
from .views import adopt_expert
from .views import authorization_publish2img
from .views import cancel_defense
from .views import clear_exception
from .views import create_user_hes_so
from .views import download_project_zip
from .views import download_theses_zip
from .views import download_thesis_zip
from .views import download_zip_assessment
from .views import download_zip_authorization_publish
from .views import download_zip_statement_fees
from .views import excel_addresses
from .views import excel_master_theses
from .views import excel_projects
from .views import file_upload
from .views import force_submission_progress_report
from .views import get_pdf_confidentiality_agreement
from .views import get_pdf_publishing_authorization
from .views import get_pdf_statement_of_fees
from .views import get_pdf_thesis_assessment
from .views import link_account
from .views import publish_evaluation
from .views import publish_evaluations
from .views import receive_hard_copies
from .views import search_hesso_directory
from .views import send_defense_invitations
from .views import send_reminder_defense_documents
from .views import send_reminder_defenses
from .views import send_reminder_expert_profile
from .views import send_reminder_experts
from .views import send_reminder_progress_reports
from .views import set_major
from .views import set_session
from .views import submit_remediation_objectives
from .views import toggle_assignment_reminders
from .views import validate_expert
from .views import validate_progress_reports
from .views import validate_supervisor

app_name = "tm"

urlpatterns = [
    path("", view=DashboardView.as_view(), name="dashboard"),
    path("overview", view=OverviewView.as_view(), name="overview"),
    path("add-proposal", view=ProposalCreateView.as_view(), name="add-proposal"),
    path("proposals", view=ProposalListView.as_view(), name="proposals"),
    path(
        "proposals/export",
        view=ProposalExportView.as_view(),
        name="proposals-export",
    ),
    path("proposal/<int:pk>/", view=ProposalDetailView.as_view(), name="proposal"),
    path(
        "proposal/<int:pk>/change",
        view=ProposalUpdateView.as_view(),
        name="change-proposal",
    ),
    path(
        "proposal/<int:pk>/submit",
        view=SubmitProposal.as_view(),
        name="submit-proposal",
    ),
    path(
        "proposal/<int:pk>/withdraw",
        view=WithdrawProposal.as_view(),
        name="withdraw-proposal",
    ),
    path(
        "proposal/<int:pk>/review",
        view=AddReviewProposal.as_view(),
        name="review-proposal",
    ),
    path(
        "proposal/<int:pk>/supervisor",
        view=SupervisorSuggestion.as_view(),
        name="supervisor-suggestion-proposal",
    ),
    path("assignments", view=AssignmentsListView.as_view(), name="assignments"),
    path(
        "assignments/validation",
        view=AssignmentsToValidateListView.as_view(),
        name="assignments-to-validate",
    ),
    path(
        "assignment/<int:pk>/validated",
        validate_supervisor,
        {"decision": "validated"},
        name="assignments-decision-validated",
    ),
    path(
        "assignment/<int:pk>/rejected",
        validate_supervisor,
        {"decision": "rejected"},
        name="assignments-decision-rejected",
    ),
    path(
        "assignment/<int:pk>/acceptance",
        view=AssignmentAcceptance.as_view(),
        name="assignments-acceptance",
    ),
    path(
        "assignment/<int:pk>/link-account",
        link_account,
        name="assignments-link-account",
    ),
    path(
        "assignment/<int:pk>/reminders",
        toggle_assignment_reminders,
        name="assignments-toggle-reminders",
    ),
    path("dispositions", view=DispositionListView.as_view(), name="dispositions"),
    path(
        "disposition/create",
        view=DispositionCreateView.as_view(),
        name="add-disposition",
    ),
    path(
        "disposition/<int:pk>/",
        view=DispositionDetailView.as_view(),
        name="disposition",
    ),
    path(
        "disposition/<int:pk>/change",
        view=DispositionUpdateView.as_view(),
        name="change-disposition",
    ),
    path(
        "disposition/<int:pk>/evaluate",
        view=DispositionEvaluateView.as_view(),
        name="evaluate-disposition",
    ),
    path(
        "disposition/<int:pk>/evaluate-methodology",
        view=DispositionEvaluateMethodologyView.as_view(),
        name="evaluate-methodology-disposition",
    ),
    path(
        "disposition/<int:pk>/submit",
        view=DispositionSubmitView.as_view(),
        name="submit-disposition",
    ),
    path(
        "disposition/<int:pk>/publish",
        publish_evaluation,
        name="publish-evaluation-disposition",
    ),
    path(
        "disposition/<int:pk>/add-co-supervisor",
        add_supervisor,
        name="add-co-supervisor-disposition",
    ),
    path("dispositions/download", download_project_zip, name="download-dispositions"),
    path("dispositions/export", excel_projects, name="excel-export-dispositions"),
    path(
        "dispositions/publish",
        publish_evaluations,
        name="publish-evaluations-dispositions",
    ),
    path("library", view=LibraryListView.as_view(), name="library"),
    path("library/<int:pk>/", view=LibraryDetailView.as_view(), name="library-detail"),
    path(
        "calendar/<int:pk>/",
        view=CalendarDetailView.as_view(),
        name="calendar-detail",
    ),
    path(
        "step/<int:pk>/delete",
        view=DeleteStepFromProposal.as_view(),
        name="delete-step",
    ),
    path("set-session/<int:session_id>/", set_session, name="set-session"),
    path("set-major/<int:major_id>/", set_major, name="set-major"),
    path(
        "confirm/",
        TemplateView.as_view(template_name="tm/proposalworkflow_confirm.html"),
        name="confirm",
    ),
    path("attempt/", view=AttemptDetailView.as_view(), name="attempt-resolver"),
    path("attempt/<int:pk>/", view=AttemptDetailView.as_view(), name="attempt"),
    path(
        "attempt/<int:pk>/add-leave",
        view=PersonalLeaveCreateView.as_view(),
        name="add-leave",
    ),
    path("leaves", view=PersonalLeaveListView.as_view(), name="leaves"),
    path(
        "leave/<int:pk>/change",
        view=PersonalLeaveUpdateView.as_view(),
        name="change-leave",
    ),
    path(
        "leave/<int:pk>/delete",
        view=PersonalLeaveDeleteView.as_view(),
        name="delete-leave",
    ),
    path(
        "attempt/<int:pk>/add-exception",
        view=StudentExceptionCreateView.as_view(),
        name="add-exception",
    ),
    path(
        "exception/<int:pk>/",
        view=StudentExceptionDetailView.as_view(),
        name="exception",
    ),
    path(
        "exception/<int:pk>/change",
        view=StudentExceptionUpdateView.as_view(),
        name="change-exception",
    ),
    path("exception/<int:pk>/clear", clear_exception, name="clear-exception"),
    path("exceptions", view=StudentExceptionListView.as_view(), name="exceptions"),
    path(
        "attempt/<int:pk>/add-progress-report",
        view=ProgressReportCreateView.as_view(),
        name="add-progress-report",

config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from apps.tm.views import HomeView
from apps.utils.views import set_language

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path("i18n/set_language/<str:user_language>", set_language, name="set_language"),
    # Wagtail
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("pages/", include(wagtail_urls)),
    # User management
    path("users/", include("apps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Switch AAI
    path("shib/", include("apps.shibboleth.urls", namespace="shibboleth")),
    # TM
    path("tm/", include("apps.tm.urls", namespace="tm")),
    path("celery-progress/", include("celery_progress.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls)), *urlpatterns]

apps/templates/tm/attempt_detail.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  {% trans "Attempt"|capfirst %}
{% endblock %}
{% block content %}
  {% include "tm/snippets/attempt_header.html" with attempt=object %}
  <hr />
  <div class="row">
    <div class="col-sm-12 col-md-6 col-lg-6 col-xl-4 d-flex align-items-stretch">
      {% include "tm/snippets/personal_leave_card.html" with attempt=object %}
    </div>
    <div class="col-sm-12 col-md-6 col-lg-6 col-xl-4 d-flex align-items-stretch">
      {% include "tm/snippets/student_exception_card.html" with attempt=object %}
    </div>
    <div class="col-sm-12 col-md-6 col-lg-6 col-xl-4 d-flex align-items-stretch">
      {% include "tm/snippets/attempt_status_card.html" with attempt=object %}
    </div>
    <div class="col-sm-12 col-md-6 col-lg-6 col-xl-4 d-flex align-items-stretch">
      <div class="card w-100">
        <div class="card-header">
          <h5 class="card-title mb-0">{% translate "calendar"|capfirst %}</h5>
        </div>
        {% include "tm/snippets/calendar_card.html" with calendar=object.calendar %}
      </div>
    </div>
  </div>
{% endblock %}
{% block modal %}
{% endblock modal %}

apps/templates/tm/create_account.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  {% trans "create account from the HES-SO directory"|capfirst %}
{% endblock %}
{% block content %}
  <style>
    .autocomplete-input-black {
      border: 1px solid #000000;
    }
  </style>
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          <form method="post">
            {% csrf_token %}
            {% blocktrans %}
                <p>You can create a new account from the HES-SO directory.
                  Please search for the name in the directory and select the corresponding person.
                </p>
              {% endblocktrans %}
            <p class="text-danger">
              {% translate "It is currently not possible to automatically create an account for an external user. Please contact support in this case." %}
            </p>
            <div class="autocomplete mb-3" id="autocomplete-account">
              <input class="autocomplete-input autocomplete-input-black"
                     placeholder="{% translate 'Search for a user in the HES-SO directory...' %}"
                     aria-label="Search" />
              <ul class="autocomplete-result-list">
              </ul>
            </div>
            {{ form|crispy }}
            <button type="submit" value="create" class="btn btn-outline-success">{% trans 'create account'|capfirst %}</button>
          </form>
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block inline_javascript %}
  {{ form.media }}
  <script>
    document.addEventListener("DOMContentLoaded", function() {
      const hesso_input = document.getElementById('id_hesso_id');

      new Autocomplete('#autocomplete-account', {
        search: input => {
          //const url = `{% url 'tm:attempts-autocomplete' %}?people=${encodeURI(input)}`
          const url = `https://mscba.hes-so.ch/tm/people-search?people=${encodeURI(input)}`

          return new Promise(resolve => {
            if (input.length < 4) {
              return resolve([])
            }

            fetch(url)
              .then(response => response.json())
              .then(data => {
                resolve(data.results)
              })
          })
        },

        renderResult: (result, props) => `
              <li ${props}>
                <span class="hesso-people-name">${result.display_name}</span>
                <span class="hesso-people-school">${result.schools}</span>
              </li>
          `,

        getResultValue: result => result.display_name,

        onSubmit: result => {
          hesso_input.value = result.id;
        }
      })
    })
  </script>
{% endblock inline_javascript %}

apps/templates/tm/defense_form.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  {% trans "thesis"|capfirst %}
{% endblock %}
{% block content %}
  {% include "tm/snippets/attempt_header.html" with attempt=thesis.attempt %}
  <div class="row">
    <div class="col-12">
      <div class="card">
        <div class="card-body">
          {% crispy form %}
          {% if perms.tm.can_override_defense_session_dates %}
            <button class="btn btn-outline-danger" id="disableMinMaxButton">
              {% translate "override session dates"|capfirst %}
            </button>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block inline_javascript %}
  {{ form.media }}
  <script src="{% static 'js/flatpickr.l10n.fr.js' %}"></script>
  {% comment %} djlint:off {% endcomment %}
  <script>
    const defenseSessionStart = "{{ thesis.attempt.current_calendar.defense_start|date:'Y-m-d' }}"
    const defenseSessionEnd = "{{ thesis.attempt.current_calendar.defense_end|date:'Y-m-d' }}"
    const defenseDate = "{{ object.defense_date|date:'Y-m-d H:i' }}"

    // Calculate the start and end times for the day of defenseDate
    // This is used to enable the date picker if the defense date is outside the defense session
    const defenseDateObj = new Date(defenseDate);
    const defenseDateStart = defenseDateObj.setHours(0, 0, 0, 0);
    const defenseDateEnd = defenseDateObj.setHours(23, 59, 59, 0);

    document.addEventListener("DOMContentLoaded", function() {
        const placeField = document.getElementById("id_place");
        const roomField = document.getElementById("div_id_room");
        const otherLocationField = document.getElementById("div_id_other_location");

        // Set the initial display state
        if (placeField.value === "Other") {
          otherLocationField.style.display = "block";
          if (roomField) {
            roomField.style.display = "none";
          }
        } else {
          otherLocationField.style.display = "none";
          if (roomField) {
            roomField.style.display = "block";
          }
        }

        placeField.addEventListener("change", function() {
            if (placeField.value === "Other") {
                otherLocationField.style.display = "block";
                if (roomField) {
                  roomField.style.display = "none";
                }
            } else {
                otherLocationField.style.display = "none";
                if (roomField) {
                  roomField.style.display = "block";
                }
            }
        });

        // Date picker
        const datePicker = flatpickr("#id_defense_date", {
            enableTime: true,
            dateFormat: "Y-m-d H:i",
            defaultDate: defenseDate,
            time_24hr: true,
            {% if LANGUAGE_CODE %}
            locale: "fr",
            {% else %}
            locale: "fr",
            {% endif %}
            enable: [
              {
                from: defenseSessionStart,
                to: defenseSessionEnd,
              },
              {
                from: defenseDateStart,
                to: defenseDateEnd,
              },
            ],
        });

        // Button to disable minDate and maxDate
        const disableMinMaxButton = document.getElementById("disableMinMaxButton");

        disableMinMaxButton.addEventListener("click", function() {
            // Disable minDate and maxDate by setting them to null
        datePicker.set("enable", [{
          from: new Date().fp_incr(-365),
          to: new Date().fp_incr(365)
        }]);
        });

    });
</script>
{% comment %} djlint:on {% endcomment %}
{% endblock inline_javascript %}

apps/templates/tm/import_students_progress.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  {% trans "import students"|capfirst %}
{% endblock %}
{% block content %}
  <div class="row mb-4">
    <div class="col-md-12">
      <h1>{% translate "import students"|capfirst %}</h1>
      <p>{% translate "Task UID" %}: {{ task_id }}</p>
      <div class="progress-wrapper">
        <div id="progress-bar"
             class="progress-bar"
             style="background-color: #68a9ef;
                    width: 0%">&nbsp;</div>
      </div>
      <div id="progress-bar-message" class="mt-2">{% translate "Waiting for progress to start..." %}</div>
      <div id="celery-result" class="mt-4"></div>
    </div>
  </div>
{% endblock %}
{% comment %} djlint:off {% endcomment %}
{% block inline_javascript %}
  <script src="{% static 'celery_progress/celery_progress.js' %}"></script>
  <script>
    const progressUrl = "{% url 'celery_progress:task_status' task_id %}";

    function customResult(resultElement, result) {
      const h2Element = document.createElement("h2");
      h2Element.textContent = "{% translate "Imported Students" %}";

      const h2ErrorElement = document.createElement("h2");
      h2ErrorElement.textContent = "{% translate "Import Errors" %}";

      const pErrorElement = document.createElement("p");
      pErrorElement.textContent = "{% translate "The following ISA IDs were not found in the directory and could not be imported!" %}";

      const ulElement = document.createElement("ul");
      for (let i = 0; i < result["attempts"].length; i++) {
        const liElement = document.createElement("li");
        liElement.textContent = result["attempts"][i]["student"];
        ulElement.appendChild(liElement);
      }

      resultElement.appendChild(h2Element);
      resultElement.appendChild(ulElement);
      resultElement.appendChild(h2ErrorElement);

      if (result["errors"] !== null && Array.isArray(result["errors"])) {
        resultElement.appendChild(pErrorElement);
        const ulErrorElement = document.createElement("ul");
        for (let i = 0; i < result["errors"].length; i++) {
          const liErrorElement = document.createElement("li");
          liErrorElement.textContent = result["errors"][i];
          ulErrorElement.appendChild(liErrorElement);
        }
        resultElement.appendChild(ulErrorElement);
      } else {
        const pNoErrorElement = document.createElement("p");
        pNoErrorElement.textContent = "No errors";
        resultElement.appendChild(pNoErrorElement);
      }

    }

    document.addEventListener("DOMContentLoaded", function() {
      CeleryProgressBar.initProgressBar(progressUrl, {
        onResult: customResult,
      });
    });
</script>
{% endblock inline_javascript %}
{% comment %} djlint:on {% endcomment %}

apps/templates/tm/masterthesis_mailing_list.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block title %}
  {% trans "theses mailing"|capfirst %}
{% endblock %}
{% block javascript %}
  {{ block.super }}
  <link href="https://cdn.jsdelivr.net/npm/simple-datatables@latest/dist/style.css"
        rel="stylesheet"
        type="text/css" />
  <script src="https://cdn.jsdelivr.net/npm/simple-datatables@latest"
          type="text/javascript"></script>
{% endblock javascript %}
{% block content %}
  <div class="row mb-4">
    <div class="col-md-12">
      <table class="table" id="reportsTable">
        <thead>
          <tr>
            <th>{% trans 'student'|capfirst %}</th>
            <th>{% trans 'role'|capfirst %}</th>
            <th>{% trans 'name'|capfirst %}</th>
            <th>{% trans 'address'|capfirst %}</th>
            <th>{% translate 'additional address'|capfirst %}</th>
            <th>{% translate 'zip code'|capfirst %}</th>
            <th>{% translate 'city'|capfirst %}</th>
          </tr>
        </thead>
        <tbody>
          {% for thesis in object_list %}
            {% if thesis.paper_submission_supervisor %}
              <tr>
                <td>
                  <a href="{% url 'tm:view-thesis' thesis.id %}">{{ thesis.attempt.student.name }}</a>
                </td>
                <td>{% translate "supervisor"|capfirst %}</td>
                <td>{{ thesis.supervisor.name }}</td>
                <td>{{ thesis.supervisor.address }}</td>
                <td>{{ thesis.supervisor.additional_address }}</td>
                <td>{{ thesis.supervisor.zip_code }}</td>
                <td>{{ thesis.supervisor.city }}</td>
              </tr>
            {% endif %}
            {% if thesis.paper_submission_expert %}
              <tr>
                <td>
                  <a href="{% url 'tm:view-thesis' thesis.id %}">{{ thesis.attempt.student.name }}</a>
                </td>
                <td>{% translate "expert"|capfirst %}</td>
                <td>{{ thesis.expert.name }}</td>
                <td>{{ thesis.expert.address }}</td>
                <td>{{ thesis.expert.additional_address }}</td>
                <td>{{ thesis.expert.zip_code }}</td>
                <td>{{ thesis.expert.city }}</td>
              </tr>
            {% endif %}
          {% endfor %}
        </tbody>
      </table>
      <a href="{% url 'tm:mailing-excel-theses' %}"
         class="btn btn-outline-primary"><i class="fa fa-file-excel"></i> {% translate "Export mailing addresses"|capfirst %}</a>
    </div>
  </div>
{% endblock %}
{% block inline_javascript %}
  <script>
    const dataTable = new simpleDatatables.DataTable("#reportsTable", {
      perPage: 25,
    })
  </script>
{% endblock inline_javascript %}

apps/templates/tm/personalleave_form.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  {% trans "personal leave"|capfirst %}
{% endblock %}
{% block content %}
  {% include "tm/snippets/attempt_header.html" with attempt=attempt %}
  <hr />
  <div class="row mb-4">
    <div class="col-md-12">{% crispy form %}</div>
  </div>
  {% if object and perms.tm.delete_personalleave %}
    <div class="alert alert-danger" role="alert">
      <div class="alert-message">
        <h5>{% translate "Delete personal leave" %}</h5>
        <p>
          {% translate "In the event of an error, you can correct the dates on the certificate and the calendar will be recalculated. If you need to delete a certificate, a new calendar will be recalculated and the people concerned will be informed by e-mail." %}
        </p>
        <a href="{% url 'tm:delete-leave' object.id %}" class="btn btn-danger">{% translate "Delete this personal leave" %}</a>
      </div>
    </div>
  {% endif %}
{% endblock %}
{% block inline_javascript %}
  {{ form.media }}
  <script data-first_day_leave="{{ object.first_day_leave|date:'Y-m-d' }}" data-last_day_leave="{{ object.last_day_leave|date:'Y-m-d' }}">
    const data = document.currentScript.dataset;
    const firstDayLeave = data.first_day_leave;
    const lastDayLeave = data.last_day_leave;

    document.addEventListener("DOMContentLoaded", function() {

      // Date picker
      flatpickr("#id_first_day_leave", {
        dateFormat: "Y-m-d",
        defaultDate: firstDayLeave,
        onChange: function(selectedDates, dateStr, instance) {
          endDate.set("minDate", dateStr);
        },
      });

      const endDate = flatpickr("#id_last_day_leave", {
        dateFormat: "Y-m-d",
        defaultDate: lastDayLeave,
      });
    });
  </script>
{% endblock inline_javascript %}

apps/templates/tm/studentexception_detail.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  {% trans "student exception"|capfirst %}
{% endblock %}
{% block content %}
  {% include "tm/snippets/attempt_header.html" with attempt=object.attempt %}
  <hr />
  <div class="row">
    <div class="col">
      <div class="card">
        <div class="card-header">
          <h5 class="card-title mb-0">{% translate "special situation"|capfirst %}</h5>
        </div>
        <div class="card-body">
          <p class="h4">
            <strong>{{ object.reason }}</strong>
          </p>
          <p>
            {% trans 'This situation prevents' %}
            {% if object.block_tm %}
              <strong>{% trans "the completion of the master's thesis" %}</strong>
            {% endif %}
            {% if object.block_defense %}
              {% if object.block_tm %}
                {% trans "and" %}
              {% endif %}
              <strong>{% trans "the defense of the master's thesis" %}</strong>
            {% endif %}
          </p>
          <p>
            {% trans 'Probable resolution date' %}: <strong>{{ object.probable_resolution_date|date:"SHORT_DATE_FORMAT" }}</strong>
          </p>
          <p>
            <i>{% blocktranslate with user=object.created_by date=object.creation_date %}Recorded by {{ user }} on {{ date }}.{% endblocktranslate %}</i>
          </p>
          {% if perms.tm.change_studentexception %}
            <a href="{% url 'tm:change-exception' object.id %}"
               class="btn btn-outline-primary">{% translate 'edit'|capfirst %}</a>
          {% endif %}
          {% if perms.tm.can_clear_studentsexceptions %}
            <button type="button"
                    class="btn btn-success"
                    data-bs-toggle="modal"
                    data-bs-target="#confirmClearing">{% translate 'clear the exception'|capfirst %}</button>
          {% endif %}
        </div>
      </div>
    </div>
  </div>
{% endblock %}
{% block modal %}
  <div class="modal fade"
       id="confirmClearing"
       data-bs-backdrop="static"
       data-bs-keyboard="false"
       tabindex="-1"
       aria-labelledby="confirmClearingLabel"
       aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered">
      <div class="modal-content">
        <div class="modal-header bg-success">
          <h5 class="modal-title text-white" id="confirmClearingLabel">{% trans 'Clear the student exception' %}</h5>
          <button type="button"
                  class="btn-close"
                  data-bs-dismiss="modal"
                  aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <p>
            {% translate "By resolving the student's particular situation, he/she will be able to continue with his/her Master's thesis (unless other particular situations prevent this)." %}
          </p>
          <p>{% translate "If this is the student's last special situation, he/she will be notified." %}</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">{% trans 'close'|capfirst %}</button>
          <a href="{% url 'tm:clear-exception' object.id %}"
             class="btn btn-outline-success">{% trans 'clear the exception'|capfirst %}</a>
        </div>
      </div>
    </div>
  </div>
{% endblock modal %}