apps/users/urls.py
from django.urls import path

from apps.users.views import ExpertAutocomplete
from apps.users.views import ExpertCreateView
from apps.users.views import ExpertStandaloneCreateView
from apps.users.views import user_detail_view
from apps.users.views import user_redirect_view
from apps.users.views import user_update_view
from apps.users.views import validate_expert

app_name = "users"
urlpatterns = [
    path(
        "expert-autocomplete/<int:attempt_id>",
        ExpertAutocomplete.as_view(),
        name="expert-autocomplete",
    ),
    path("expert-create/", ExpertCreateView.as_view(), name="expert-create"),
    path(
        "expert-standalone-create/",
        ExpertStandaloneCreateView.as_view(),
        name="expert-standalone-create",
    ),
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("~validate/", validate_expert, name="expert-validation"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from apps.tm.views import HomeView
from apps.utils.views import set_language

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path("i18n/set_language/<str:user_language>", set_language, name="set_language"),
    # Wagtail
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("pages/", include(wagtail_urls)),
    # User management
    path("users/", include("apps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Switch AAI
    path("shib/", include("apps.shibboleth.urls", namespace="shibboleth")),
    # TM
    path("tm/", include("apps.tm.urls", namespace="tm")),
    path("celery-progress/", include("celery_progress.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls)), *urlpatterns]

apps/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models
from django.urls import reverse
from django.utils.functional import cached_property
from django.utils.translation import gettext_lazy as _


class User(AbstractUser):
    """
    Default custom user model for MScBA TM Manager.
    If adding fields that need to be filled at user signup,
    check forms.SignupForm and forms.SocialSignupForms accordingly.
    """

    UNKNOWN = 0
    MALE = 1
    FEMALE = 2
    NA = 9
    GENDER = [
        (UNKNOWN, _("not known")),
        (MALE, _("male")),
        (FEMALE, _("female")),
        (NA, _("not applicable")),
    ]

    name = models.CharField(_("Name of User"), blank=True, max_length=255)
    gender = models.IntegerField(
        _("gender"),
        blank=True,
        default=UNKNOWN,
        choices=GENDER,
    )
    is_student = models.BooleanField(default=False)
    is_supervisor = models.BooleanField(default=False)
    is_expert = models.BooleanField(default=False)
    is_mh = models.BooleanField(default=False)
    profile_linkedin = models.URLField(
        max_length=200,
        verbose_name=_("LinkedIn profile"),
        null=True,
        blank=True,
    )

    majors = models.ManyToManyField("tm.Major", blank=True)

    attempt = models.ForeignKey(
        "tm.Attempt",
        related_name="users",
        blank=True,
        null=True,
        on_delete=models.SET_NULL,
        verbose_name=_("attempt"),
    )

    # Personal information for experts
    address = models.CharField(_("address"), max_length=255, null=True, blank=True)
    additional_address = models.CharField(
        _("additional address"),
        max_length=255,
        blank=True,
        null=True,
    )
    zip_code = models.CharField(
        _("zip code"),
        max_length=15,
        null=True,
        blank=True,
        help_text=_(
            "Please add the country code before the postal code if you are outside of "
            "Switzerland (e.g. F-71640).",
        ),
    )
    city = models.CharField(_("city"), max_length=255, null=True, blank=True)

    highest_degree = models.CharField(
        _("highest degree"),
        max_length=255,
        null=True,
        blank=True,
    )
    year_of_graduation = models.IntegerField(
        _("year of graduation"),
        null=True,
        blank=True,
    )
    current_job = models.CharField(
        _("current job"),
        max_length=255,
        null=True,
        blank=True,
    )
    current_company = models.CharField(
        _("current company"),
        max_length=255,
        null=True,
        blank=True,
    )

    profile_validated = models.BooleanField(default=False)
    profile_validation_date = models.DateTimeField(null=True, blank=True)

    language = models.CharField(_("language"), max_length=10, default="fr")

    class Meta:
        permissions = [
            ("can_search_directory", _("Can search peolple in the HES-SO directory")),
            ("can_adopt_user", _("Can adopt a user")),
            ("can_view_all_experts", _("Can view all experts")),
        ]

    @cached_property
    def address_line(self):
        line = ""
        if self.address:
            line += self.address + ", "
        if self.additional_address:
            line += self.additional_address + ", "
        if self.zip_code:
            line += self.zip_code + " "
        if self.city:
            line += self.city
        return line

    def __str__(self):
        return f"{self.name}"

    def get_absolute_url(self):
        """Get url for user's detail view.

        Returns:
            str: URL for user detail.

        """
        return reverse("users:detail", kwargs={"username": self.username})

apps/users/views.py
from dal import autocomplete
from django.contrib import messages
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db import transaction
from django.db.models import Q
from django.shortcuts import redirect
from django.urls import reverse
from django.urls import reverse_lazy
from django.utils import timezone
from django.utils.translation import gettext_lazy as _
from django.views.generic import CreateView
from django.views.generic import DetailView
from django.views.generic import RedirectView
from django.views.generic import UpdateView
from django_addanother.views import CreatePopupMixin

from .forms import ExpertCreateForm  # , ExpertValidateForm
from .forms import ExpertUpdateForm  # , ExpertValidateForm
from .tasks import send_expert_welcome_message

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, SuccessMessageMixin, UpdateView):
    model = User
    success_message = _("Information successfully updated")

    def get_success_url(self):
        assert (
            self.request.user.is_authenticated
        )  # for mypy to know that the user is authenticated
        return self.request.user.get_absolute_url()

    def get_object(self):
        return self.request.user

    def get_form(self):
        if self.request.user.is_expert:
            self.form_class = ExpertUpdateForm
        else:
            self.form_class = ExpertUpdateForm
        return super().get_form()


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()


class ExpertAutocomplete(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        from apps.tm.models import Attempt

        if not self.request.user.is_authenticated:
            return User.objects.none()

        attempt_id = self.kwargs.get("attempt_id", None)

        qs = User.objects.filter(Q(is_expert=True) | Q(is_supervisor=True)).order_by(
            "name",
        )

        if attempt_id:
            # Get the attempt
            attempt = Attempt.objects.get(id=attempt_id)

            # Filter the queryset based on the major of the attempt
            qs = qs.filter(majors__in=[attempt.major])

        if self.q:
            qs = qs.filter(
                Q(name__istartswith=self.q)
                | Q(first_name__istartswith=self.q)
                | Q(last_name__istartswith=self.q),
            )

        return qs


class ExpertCreateView(
    LoginRequiredMixin,
    SuccessMessageMixin,
    CreatePopupMixin,
    CreateView,
):
    model = User
    form_class = ExpertCreateForm
    success_message = _("Information successfully updated")
    template_name = "users/expert_form.html"

    def form_valid(self, form):
        form.instance.is_expert = True
        form.instance.username = (
            f"{form.instance.first_name.lower()}.{form.instance.last_name.lower()}"
        )
        form.instance.name = f"{form.instance.first_name} {form.instance.last_name}"
        response = super().form_valid(form)
        self.object.set_unusable_password()
        self.object.majors.add(*self.request.user.majors.all())
        self.object.language = self.request.user.language
        self.object.save()
        transaction.on_commit(
            lambda: send_expert_welcome_message.delay(
                self.object.id,
                self.request.user.id,
            ),
        )
        return response


class ExpertStandaloneCreateView(LoginRequiredMixin, SuccessMessageMixin, CreateView):
    model = User
    form_class = ExpertCreateForm
    success_message = _("Information successfully updated")
    template_name = "users/expert_form.html"
    success_url = reverse_lazy("tm:experts")

    def form_valid(self, form):
        form.instance.is_expert = True
        form.instance.username = (
            f"{form.instance.first_name.lower()}.{form.instance.last_name.lower()}"
        )
        form.instance.name = f"{form.instance.first_name} {form.instance.last_name}"
        response = super().form_valid(form)
        self.object.set_unusable_password()
        self.object.majors.add(*self.request.user.majors.all())
        self.object.language = self.request.user.language
        self.object.save()
        transaction.on_commit(
            lambda: send_expert_welcome_message.delay(
                self.object.id,
                self.request.user.id,
            ),
        )
        return response


def validate_expert(request):
    user = request.user
    user.profile_validated = True
    user.profile_validation_date = timezone.now()
    user.save()
    messages.add_message(
        request,
        messages.SUCCESS,
        _("Your profile has been validated. Thank you!."),
    )
    return redirect("users:detail", username=user.username)

apps/templates/users/expert_form.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}
  {% trans "invite new expert"|capfirst %}
{% endblock %}
{% block content %}
  <h2>{% translate 'expert proposal'|capfirst %}</h2>
  {% blocktranslate %}
    <p>Please enter the information required to register a new expert. The expert will be automatically contacted to complete his/her personal information.</p>
    <p>Once the information is complete, the expert may be assigned to the master's thesis.</p>
  {% endblocktranslate %}
  {% crispy form %}
{% endblock content %}

apps/templates/users/user_detail.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block title %}
  {% trans "profile"|capfirst %}
{% endblock %}
{% block content %}
  <div class="row">
    <div class="col">
      <h2>{{ object.name }}</h2>
      <p>
        {% for major in object.majors.all %}
          {{ major }}
          {% if not forloop.last %}/{% endif %}
        {% empty %}{% trans 'major not defined'|capfirst %}
        {% endfor %}
      </p>
      <p>
        {% trans 'contact address'|capfirst %}:
        {% if request.user.email %}
          <a href="mailto:{{ request.user.email }}" class="alert-link">{{ request.user.email }}</a>
        {% else %}
          {% trans 'email address undefined'|capfirst %}
        {% endif %}
        <br />
        {% trans 'profile'|capfirst %}:
        {% if object.is_mh %}
          <span class="badge bg-light-dark">{% trans 'Module head' %}</span>
        {% endif %}
        {% if object.is_supervisor %}
          <span class="badge bg-light-dark">{% trans 'Supervisor' %}</span>
        {% endif %}
        {% if object.is_expert %}
          <span class="badge bg-light-dark">{% trans 'Expert' %}</span>
        {% endif %}
        {% if object.is_student %}
          <span class="badge bg-light-dark">{% trans 'Student' %}</span>
        {% endif %}
        {% if not object.is_mh and not object.is_supervisor and not object.is_student and not object.is_expert %}
          <span class="badge bg-danger">{% trans 'Profile undefined' %}</span>
        {% endif %}
        <br />
        {% trans 'UID'|capfirst %}: {{ object.username }}
      </p>
    </div>
  </div>
  <div class="row">
    {% for attempt in object.attempts.all %}
      <div class="col-sm-6 d-flex">
        <div class="card flex-fill">
          <div class="card-header">
            <h5 class="card-title mb-0">
              {% trans 'session'|capfirst %} {{ attempt.session }}
              {% if attempt.archived %}
                <span class="badge bg-secondary ms-2">{% trans 'archived'|capfirst %}</span>
              {% elif object.attempt == attempt %}
                <span class="badge bg-success ms-2">{% trans 'current'|capfirst %}</span>
              {% endif %}
            </h5>
          </div>
          <div class="card-body">
            <p>{% trans 'major'|capfirst %} {{ attempt.major }}</p>
            <p>{% trans 'thesis start'|capfirst %} {{ attempt.current_calendar.thesis_start }}</p>
            <p>
              {% trans 'thesis end'|capfirst %} <strong>{{ attempt.current_calendar.thesis_end }}</strong>
            </p>
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
  {% if object.is_expert %}
    <div class="row">
      <div class="col-12">
        <div class="card">
          <div class="card-body">
            <h4 class="mb-4">{% translate "expert profile"|capfirst %}</h4>
            <p>
              <strong>{% translate "majors"|capfirst %}</strong>:
              {% for major in object.majors.all %}
                {{ major }}
                {% if not forloop.last %}/{% endif %}
              {% empty %}{% trans 'major not defined'|capfirst %}
              {% endfor %}
            </p>
            <p>
              <i class="fa fa-building"></i>
              {% if object.current_job %}
                {{ object.current_job }}
              {% else %}
                {% translate "current position not defined"|capfirst %}
              {% endif %}
              {% if object.current_company %}
                ({{ object.current_company }})
              {% else %}
                ({% translate "current company not defined" %})
              {% endif %}
            </p>
            <p>
              <i class="fa-brands fa-linkedin"></i>
              {% if object.profile_linkedin %}
                <a href="{{ object.profile_linkedin }}" target="_blank">LinkedIn</a>
              {% else %}
                {% translate "LinkedIn profile not defined"|capfirst %}
              {% endif %}
            </p>
            <p>
              <i class="fa fa-graduation-cap"></i>
              {% if object.highest_degree %}
                {{ object.highest_degree }} ({{ object.year_of_graduation }})
              {% else %}
                {% translate 'education not defined'|capfirst %}
              {% endif %}
            </p>
            <p>
              <strong>{% translate "address"|capfirst %}</strong>
              <br />
              <i>{% translate "Master's theses and other administrative documents will be sent to this address." %}</i>
            </p>
            <p>
              {% if object.address %}
                {{ object.name }}
                <br />
                {{ object.address }}
                <br />
                {% if object.additional_address %}
                  {{ object.additional_address }}
                  <br />
                {% endif %}
                {{ object.zip_code }} {{ object.city }}
              {% else %}
                {% translate 'current address not defined'|capfirst %}
              {% endif %}
            </p>
            <p>
              <a href="{% url 'users:update' %}" class="btn btn-outline-primary">{% translate 'update profile'|capfirst %}</a>
            </p>
            {% if not object.profile_validated %}
              <div class="alert alert-warning" role="alert">
                <div class="alert-message">
                  <h4 class="alert-heading">{% translate 'Profile not validated!' %}</h4>
                  {% if not object.current_job or not object.highest_degree %}
                    <p>{% translate "Some required information is missing. Please edit the profile and add the missing data." %}</p>
                    <p>{% translate "When all the information is complete, you will be able to validate your expert profile." %}</p>
                  {% else %}
                    <p>
                      <a href="{% url 'users:expert-validation' %}" class="btn btn-success">{% translate 'validate my profile and join the team of experts'|capfirst %}</a>
                    </p>
                  {% endif %}
                </div>
              </div>
            {% endif %}
          </div>
        </div>
      </div>
    </div>
  {% endif %}
{% endblock %}

apps/templates/users/user_form.html
{% extends "base.html" %}

{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}
{% block content %}
  {% crispy form %}
{% endblock %}

apps/templates/users/user_list.html
{% extends "base.html" %}

{% load i18n %}
{% load static %}

{% block title %}
  {% trans "experts"|capfirst %}
{% endblock %}
{% block content %}
  <div class="row mb-4">
    <div class="col-md-12">
      {% if perms.users.add_user %}
        <div class="row">
          <p>
            <a class="btn btn-outline-primary float-end ms-1"
               href="{% url 'users:expert-standalone-create' %}">{% translate 'add external expert'|capfirst %}</a>
            <a class="btn btn-outline-primary float-end"
               href="{% url 'tm:create-user-hes-so' %}">{% translate 'add expert from HES-SO directory'|capfirst %}</a>
          </p>
        </div>
      {% endif %}
      {% if perms.users.can_adopt_user %}
        <p>
          {% translate "You can adopt an expert in your major by clicking the <b>Adopt</b> button." %}
        </p>
      {% endif %}
      <table class="table table-striped" id="exceptionsTable">
        <thead>
          <tr>
            <th>{% trans 'name'|capfirst %}</th>
            <th>{% trans 'occupation'|capfirst %}</th>
            <th>{% trans "education"|capfirst %}</th>
            <th>{% trans 'majors'|capfirst %}</th>
            {% if perms.users.can_adopt_user %}
              <th>{% trans 'adopt'|capfirst %}</th>
            {% endif %}
          </tr>
        </thead>
        <tbody>
          {% for user in object_list %}
            <tr>
              <td>
                {{ user }}
                {% if user.email %}<a href="mailto:{{ user.email }}" class="ms-1"><i class="fa fa-envelope"></i></a>{% endif %}
              </td>
              <td>
                {% if user.current_job %}
                  {{ user.current_job }}
                  {% if user.current_company %}, <i>{{ user.current_company }}</i>{% endif %}
                {% elif user.current_company %}
                  {{ user.current_company }}
                {% endif %}
                {% if user.profile_linkedin %}
                  <a href="{{ user.profile_linkedin }}" target="_blank" class="ms-1"><i class="fa-brands fa-linkedin"></i></a>
                {% endif %}
              </td>
              <td>
                {% if user.highest_degree %}
                  {{ user.highest_degree }}
                  {% if user.year_of_graduation %}({{ user.year_of_graduation }}){% endif %}
                {% endif %}
              </td>
              <td>
                {% for major in user.majors.all %}<span class="me-1 badge bg-secondary">{{ major.code }}</span>{% endfor %}
              </td>
              {% if perms.users.can_adopt_user %}
                <td class="text-center">
                  {% if current_major not in user.majors.all %}
                    <a href="{% url 'tm:adopt-expert' user.id %}"
                       class="btn btn-sm btn-outline-primary"><i class="fa fa-plus"></i></a>
                  {% endif %}
                </td>
              {% endif %}
            </tr>
          {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
{% endblock %}