apps/tm/urls.py
from django.urls import path
from django.views.generic import TemplateView

from .views import AddReviewProposal
from .views import AnonymizeDataProgressView
from .views import AnonymizeDataView
from .views import AssignmentAcceptance
from .views import AssignmentsListView
from .views import AssignmentsToValidateListView
from .views import AttemptAutocomplete
from .views import AttemptDetailView
from .views import CalendarDetailView
from .views import DashboardView
from .views import DefenseBookRoomUpdateView
from .views import DefenseCreateView
from .views import DefenseRemediationObjectives
from .views import DefensesListView
from .views import DefenseSubmitAssessment
from .views import DefenseSubmitStatementOfFees
from .views import DeleteStepFromProposal
from .views import DispositionCreateView
from .views import DispositionDetailView
from .views import DispositionEvaluateMethodologyView
from .views import DispositionEvaluateView
from .views import DispositionListView
from .views import DispositionSubmitView
from .views import DispositionUpdateView
from .views import ExpertListView
from .views import GroupsListView
from .views import ImportExportDocumentsView
from .views import ImportStudentsProgressView
from .views import ImportStudentsView
from .views import LibraryDetailView
from .views import LibraryListView
from .views import OverviewView
from .views import PersonalLeaveCreateView
from .views import PersonalLeaveDeleteView
from .views import PersonalLeaveListView
from .views import PersonalLeaveUpdateView
from .views import ProgressReportCreateView
from .views import ProgressReportDetailView
from .views import ProgressReportListView
from .views import ProgressReportSubmitView
from .views import ProgressReportUpdateView
from .views import ProgressReportView
from .views import ProposalCreateView
from .views import ProposalDetailView
from .views import ProposalExportView
from .views import ProposalListView
from .views import ProposalUpdateView
from .views import StudentExceptionCreateView
from .views import StudentExceptionDetailView
from .views import StudentExceptionListView
from .views import StudentExceptionUpdateView
from .views import SubmitProposal
from .views import SupervisorAutocomplete
from .views import SupervisorSuggestion
from .views import ThesesListView
from .views import ThesesMailingView
from .views import ThesisDetailView
from .views import ThesisExpertAcceptView
from .views import ThesisExpertDeclineView
from .views import ThesisExpertDetailView
from .views import ThesisRecordAuthorizationPublish
from .views import ThesisSubmitAuthorizationPublish
from .views import ThesisSubmitView
from .views import ThesisUpdateView
from .views import WithdrawProposal
from .views import add_supervisor
from .views import adopt_expert
from .views import authorization_publish2img
from .views import cancel_defense
from .views import clear_exception
from .views import create_user_hes_so
from .views import download_project_zip
from .views import download_theses_zip
from .views import download_thesis_zip
from .views import download_zip_assessment
from .views import download_zip_authorization_publish
from .views import download_zip_statement_fees
from .views import excel_addresses
from .views import excel_master_theses
from .views import excel_projects
from .views import file_upload
from .views import force_submission_progress_report
from .views import get_pdf_confidentiality_agreement
from .views import get_pdf_publishing_authorization
from .views import get_pdf_statement_of_fees
from .views import get_pdf_thesis_assessment
from .views import link_account
from .views import publish_evaluation
from .views import publish_evaluations
from .views import receive_hard_copies
from .views import search_hesso_directory
from .views import send_defense_invitations
from .views import send_reminder_defense_documents
from .views import send_reminder_defenses
from .views import send_reminder_expert_profile
from .views import send_reminder_experts
from .views import send_reminder_progress_reports
from .views import set_major
from .views import set_session
from .views import submit_remediation_objectives
from .views import toggle_assignment_reminders
from .views import validate_expert
from .views import validate_progress_reports
from .views import validate_supervisor

app_name = "tm"

urlpatterns = [
    path("", view=DashboardView.as_view(), name="dashboard"),
    path("overview", view=OverviewView.as_view(), name="overview"),
    path("add-proposal", view=ProposalCreateView.as_view(), name="add-proposal"),
    path("proposals", view=ProposalListView.as_view(), name="proposals"),
    path(
        "proposals/export",
        view=ProposalExportView.as_view(),
        name="proposals-export",
    ),
    path("proposal/<int:pk>/", view=ProposalDetailView.as_view(), name="proposal"),
    path(
        "proposal/<int:pk>/change",
        view=ProposalUpdateView.as_view(),
        name="change-proposal",
    ),
    path(
        "proposal/<int:pk>/submit",
        view=SubmitProposal.as_view(),
        name="submit-proposal",
    ),
    path(
        "proposal/<int:pk>/withdraw",
        view=WithdrawProposal.as_view(),
        name="withdraw-proposal",
    ),
    path(
        "proposal/<int:pk>/review",
        view=AddReviewProposal.as_view(),
        name="review-proposal",
    ),
    path(
        "proposal/<int:pk>/supervisor",
        view=SupervisorSuggestion.as_view(),
        name="supervisor-suggestion-proposal",
    ),
    path("assignments", view=AssignmentsListView.as_view(), name="assignments"),
    path(
        "assignments/validation",
        view=AssignmentsToValidateListView.as_view(),
        name="assignments-to-validate",
    ),
    path(
        "assignment/<int:pk>/validated",
        validate_supervisor,
        {"decision": "validated"},
        name="assignments-decision-validated",
    ),
    path(
        "assignment/<int:pk>/rejected",
        validate_supervisor,
        {"decision": "rejected"},
        name="assignments-decision-rejected",
    ),
    path(
        "assignment/<int:pk>/acceptance",
        view=AssignmentAcceptance.as_view(),
        name="assignments-acceptance",
    ),
    path(
        "assignment/<int:pk>/link-account",
        link_account,
        name="assignments-link-account",
    ),
    path(
        "assignment/<int:pk>/reminders",
        toggle_assignment_reminders,
        name="assignments-toggle-reminders",
    ),
    path("dispositions", view=DispositionListView.as_view(), name="dispositions"),
    path(
        "disposition/create",
        view=DispositionCreateView.as_view(),
        name="add-disposition",
    ),
    path(
        "disposition/<int:pk>/",
        view=DispositionDetailView.as_view(),
        name="disposition",
    ),
    path(
        "disposition/<int:pk>/change",
        view=DispositionUpdateView.as_view(),
        name="change-disposition",
    ),
    path(
        "disposition/<int:pk>/evaluate",
        view=DispositionEvaluateView.as_view(),
        name="evaluate-disposition",
    ),
    path(
        "disposition/<int:pk>/evaluate-methodology",
        view=DispositionEvaluateMethodologyView.as_view(),
        name="evaluate-methodology-disposition",
    ),
    path(
        "disposition/<int:pk>/submit",
        view=DispositionSubmitView.as_view(),
        name="submit-disposition",
    ),
    path(
        "disposition/<int:pk>/publish",
        publish_evaluation,
        name="publish-evaluation-disposition",
    ),
    path(
        "disposition/<int:pk>/add-co-supervisor",
        add_supervisor,
        name="add-co-supervisor-disposition",
    ),
    path("dispositions/download", download_project_zip, name="download-dispositions"),
    path("dispositions/export", excel_projects, name="excel-export-dispositions"),
    path(
        "dispositions/publish",
        publish_evaluations,
        name="publish-evaluations-dispositions",
    ),
    path("library", view=LibraryListView.as_view(), name="library"),
    path("library/<int:pk>/", view=LibraryDetailView.as_view(), name="library-detail"),
    path(
        "calendar/<int:pk>/",
        view=CalendarDetailView.as_view(),
        name="calendar-detail",
    ),
    path(
        "step/<int:pk>/delete",
        view=DeleteStepFromProposal.as_view(),
        name="delete-step",
    ),
    path("set-session/<int:session_id>/", set_session, name="set-session"),
    path("set-major/<int:major_id>/", set_major, name="set-major"),
    path(
        "confirm/",
        TemplateView.as_view(template_name="tm/proposalworkflow_confirm.html"),
        name="confirm",
    ),
    path("attempt/", view=AttemptDetailView.as_view(), name="attempt-resolver"),
    path("attempt/<int:pk>/", view=AttemptDetailView.as_view(), name="attempt"),
    path(
        "attempt/<int:pk>/add-leave",
        view=PersonalLeaveCreateView.as_view(),
        name="add-leave",
    ),
    path("leaves", view=PersonalLeaveListView.as_view(), name="leaves"),
    path(
        "leave/<int:pk>/change",
        view=PersonalLeaveUpdateView.as_view(),
        name="change-leave",
    ),
    path(
        "leave/<int:pk>/delete",
        view=PersonalLeaveDeleteView.as_view(),
        name="delete-leave",
    ),
    path(
        "attempt/<int:pk>/add-exception",
        view=StudentExceptionCreateView.as_view(),
        name="add-exception",
    ),
    path(
        "exception/<int:pk>/",
        view=StudentExceptionDetailView.as_view(),
        name="exception",
    ),
    path(
        "exception/<int:pk>/change",
        view=StudentExceptionUpdateView.as_view(),
        name="change-exception",
    ),
    path("exception/<int:pk>/clear", clear_exception, name="clear-exception"),
    path("exceptions", view=StudentExceptionListView.as_view(), name="exceptions"),
    path(
        "attempt/<int:pk>/add-progress-report",
        view=ProgressReportCreateView.as_view(),
        name="add-progress-report",

config/urls.py
# ruff: noqa
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include
from django.urls import path
from django.views import defaults as default_views
from django.views.generic import TemplateView
from wagtail import urls as wagtail_urls
from wagtail.admin import urls as wagtailadmin_urls
from wagtail.documents import urls as wagtaildocs_urls

from apps.tm.views import HomeView
from apps.utils.views import set_language

urlpatterns = [
    path("", HomeView.as_view(), name="home"),
    path(
        "about/",
        TemplateView.as_view(template_name="pages/about.html"),
        name="about",
    ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    path("i18n/set_language/<str:user_language>", set_language, name="set_language"),
    # Wagtail
    path("cms/", include(wagtailadmin_urls)),
    path("documents/", include(wagtaildocs_urls)),
    path("pages/", include(wagtail_urls)),
    # User management
    path("users/", include("apps.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Switch AAI
    path("shib/", include("apps.shibboleth.urls", namespace="shibboleth")),
    # TM
    path("tm/", include("apps.tm.urls", namespace="tm")),
    path("celery-progress/", include("celery_progress.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls)), *urlpatterns]

apps/templates/tm/snippets/attempt_header.html
{% load i18n %}

<div class="row">
  <div class="col-md-12">
    <h1>
      {{ attempt.student.name }}
      {% if attempt.retake %}
        <span class="ms-1 badge bg-secondary">{% translate 'retake'|upper %}</span>
      {% endif %}
    </h1>
    {% if settings.SETTINGS_MODULE != "config.settings.production" %}
      <p class="text-warning">
        <i>{{ attempt.student.username }}</i>
      </p>
    {% endif %}
    <h4>{% translate 'session'|capfirst %} {{ attempt.session }} - {{ attempt.major }}</h4>
    <p>
      <strong>{% trans 'supervisor'|capfirst %}</strong>:
      {% if attempt.supervisor %}
        {{ attempt.supervisor }}
      {% else %}
        {% trans 'To be defined' %}
      {% endif %}
      {% if attempt.co_supervisors %}
        <br />
        <strong>{% trans 'co-supervisor(s)'|capfirst %}</strong>:
        {{ attempt.co_supervisors.all|join:", " }}
      {% endif %}
    </p>
    <p>
      <strong>{% trans 'calendar'|capfirst %}</strong>:
      <a href="{{ attempt.current_calendar.get_absolute_url }}"
         target="_blank">{{ attempt.current_calendar.label }}</a>
      {% if attempt.current_calendar.custom %}
        <span class="ms-1 badge bg-secondary">{% translate 'custom'|upper %}</span>
      {% endif %}
      {% if attempt.current_calendar.over_session %}
        <span class="ms-1 badge bg-warning"
              data-bs-toggle="popover"
              data-bs-placement="top"
              data-bs-content="{{ attempt.current_calendar.over_session }}">{% translate 'over session'|upper %}</span>
      {% endif %}
      <br />
      <strong>{% trans 'Submission of the master thesis'|capfirst %}</strong>:
      <strong>{{ attempt.current_calendar.thesis_end|date:"SHORT_DATE_FORMAT" }}</strong>
    </p>
    {% if attempt.has_exceptions %}
      {% include 'tm/snippets/student_exception_alert.html' %}
    {% endif %}
  </div>
</div>

apps/templates/tm/snippets/attempt_status_card.html
{% load i18n %}

<div class="card w-100">
  <div class="card-header">
    <h5 class="card-title mb-0">{% translate "attempt milestones"|capfirst %}</h5>
  </div>
  <div class="card-body">
    <p>
      {% trans 'Phase 1' %} - <strong>{% trans 'Pre-proposal' %}</strong>
    </p>
    {% if attempt.proposal_done %}
      {% for proposal in attempt.accepted_proposals %}
        <p>
          <a href="{{ proposal.get_absolute_url }}">{{ proposal.title }}</a>
        </p>
      {% endfor %}
    {% else %}
      <p>{% translate 'in progress' %}</p>
    {% endif %}
    <p>
      {% trans 'Phase 2' %} - <strong>{% trans 'Final Proposal' %}</strong>
    </p>
    {% if attempt.project_done %}
      {% for project in attempt.accepted_project %}
        <p>
          <a href="{{ project.get_absolute_url }}">{{ project.title }}</a>
        </p>
      {% endfor %}
    {% else %}
      <p>{% translate 'in progress' %}</p>
    {% endif %}
    <p>
      {% trans 'Phase 3' %} - <strong>{% trans 'Master Thesis' %}</strong>
    </p>
    {% if attempt.thesis_done %}
      {% for thesis in attempt.theses.all %}
        <p>
          <a href="{{ thesis.get_absolute_url }}">{{ thesis.title }}</a>
        </p>
      {% endfor %}
    {% else %}
      <p>{% translate 'in progress' %}</p>
    {% endif %}
    <p>
      {% trans 'Phase 4' %} - <strong>{% trans 'Thesis Defense' %}</strong>
    </p>
    {% if attempt.thesis_done %}
      {% for thesis in attempt.theses.all %}
        {% for defense in thesis.defenses.all %}
          <p>{{ defense.defense_date }} {{ defense.place }} {{ defense.room }}</p>
        {% endfor %}
      {% endfor %}
    {% else %}
      <p>{% translate 'in progress' %}</p>
    {% endif %}
  </div>
</div>

apps/templates/tm/snippets/calendar_card.html
{% load i18n %}

<div class="card-body">
  <h4>
    {% trans 'Milestones and deliverables' %}
    {% if calendar.custom %}
      <span class="ms-1 badge bg-secondary">{% translate 'custom'|upper %}</span>
    {% endif %}
  </h4>
  <p>
    {% trans 'Phase 1' %} - <strong>{% trans 'Pre-proposal' %}</strong>
  </p>
  <ul>
    <li>
      {% trans 'Pre-proposal' %}: {{ calendar.proposal_start }} - <strong>{{ calendar.proposal_end }}</strong>
    </li>
    <li>{% trans 'Pre-proposal Rework' %}: {{ calendar.proposal_rework_start }} - {{ calendar.proposal_rework_end }}</li>
  </ul>
  <p>
    {% trans 'Phase 2' %} - <strong>{% trans 'Final Proposal' %}</strong>
  </p>
  <ul>
    <li>
      {% trans 'Final Proposal' %}: {{ calendar.project_start }} - <strong>{{ calendar.project_end }}</strong>
    </li>
    <li>{% trans 'Final Proposal Rework' %}: {{ calendar.project_rework_start }} - {{ calendar.project_rework_end }}</li>
  </ul>
  <p>
    {% trans 'Phase 3' %} - <strong>{% trans 'Master Thesis' %}</strong>
  </p>
  <ul>
    <li>
      {% trans 'Master Thesis' %}: {{ calendar.thesis_start }} - <strong>{{ calendar.thesis_end }}</strong>
    </li>
    <li>{% trans 'Progress Report' %}: {{ calendar.report_start }} - {{ calendar.report_end }}</li>
  </ul>
  <p>
    {% trans 'Phase 4' %} - <strong>{% trans 'Thesis Defense' %}</strong>
  </p>
  <ul>
    <li>{% trans 'Thesis Defense' %}: {{ calendar.defense_start }} - {{ calendar.defense_end }}</li>
  </ul>
  {% if calendar.over_session %}
    <p class="text-danger">
      <strong>{{ calendar.over_session }}</strong>
    </p>
  {% endif %}
</div>

apps/templates/tm/snippets/personal_leave_card.html
{% load i18n %}

<div class="card w-100">
  <div class="card-header">
    <h5 class="card-title mb-0">{% translate "personal leaves"|capfirst %}</h5>
  </div>
  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th colspan="2">{% translate 'recorded leaves'|capfirst %}</th>
        </tr>
      </thead>
      <tbody>
        {% for leave in attempt.leaves.all %}
          <tr>
            <td>
              <i class="fa {{ leave.icon }}"></i> {{ leave.get_type_of_leave_display }}
            </td>
            <td>
              {{ leave.first_day_leave }} - {{ leave.last_day_leave }} ({{ leave.duration_days }} {% translate 'days' %}
              {% if leave.duration_days != leave.effective_days %}
                ,
                <span class="text-danger">{{ leave.effective_days }} {% translate 'days' %} {% translate 'were taken into account' %}</span>
              {% endif %}
              )
              <br />
              <i>{{ leave.basis }}</i>
            </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="2">{% translate 'No recorded leaves' %}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <p class="card-text">
      {% translate 'In case of medical leave, please send your certificate to the secretariat. Once taken into account, the absence will be displayed and the calendar adapted accordingly.' %}
    </p>
    {% if perms.tm.add_personalleave %}
      <a href="{% url 'tm:add-leave' attempt.id %}" class="btn btn-primary">{% translate 'record a new leave'|capfirst %}</a>
    {% endif %}
  </div>
</div>

apps/templates/tm/snippets/student_exception_alert.html
{% load i18n %}

<div class="alert alert-danger" role="alert">
  <div class="alert-message">
    <p>
      {% translate "Special situation due to missing credits or other administrative reasons." %}
      {% translate 'This situation prevents' %}
      {% if attempt.block_tm %}
        <strong>{% trans "the completion of the master's thesis" %}</strong>
        {% if not attempt.block_defense %}.{% endif %}
      {% endif %}
      {% if attempt.block_defense %}
        {% if attempt.block_tm %}
          {% trans "and" %}
        {% endif %}
        <strong>{% trans "the defense of the master's thesis" %}</strong>.
      {% endif %}
      {% blocktranslate with resolution_date=attempt.exception_probable_resolution_date|date:"SHORT_DATE_FORMAT" %}
        The situation could be resolved on <strong>{{ resolution_date }} at the earliest</strong>, depending on the
        results of the exam session.
      {% endblocktranslate %}
    </p>
  </div>
</div>

apps/templates/tm/snippets/student_exception_card.html
{% load i18n %}

<div class="card w-100">
  <div class="card-header">
    <h5 class="card-title mb-0">{% translate "special situations"|capfirst %}</h5>
  </div>
  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th>{% translate 'current special situations'|capfirst %}</th>
        </tr>
      </thead>
      <tbody>
        {% for exception in exceptions %}
          <tr class="position-relative">
            <td>
              <a href="{{ exception.get_absolute_url }}" class="stretched-link">{{ exception.reason }}</a>
              {% if exception.block_tm %}
                <span class="ms-1 badge bg-danger">{% translate "master's thesis"|upper %}</span>
              {% endif %}
              {% if exception.block_defense %}
                <span class="ms-1 badge bg-danger">{% translate "defense"|upper %}</span>
              {% endif %}
            </td>
          </tr>
        {% empty %}
          <tr>
            <td colspan="2">{% translate 'No special situation' %}</td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    <p class="card-text">
      {% translate "Special situations preventing either the completion of the Master's thesis or its defense are listed above. If you have any questions, please contact the secretariat." %}
    </p>
    {% if perms.tm.add_studentexception %}
      <a href="{% url 'tm:add-exception' attempt.id %}"
         class="btn btn-primary">{% translate 'record a new student exception'|capfirst %}</a>
    {% endif %}
  </div>
</div>